WITH AUDIT_LOG_DATA AS 
(
   SELECT
      LA.TRANSACTIONREVISIONID TRANSACTION_REVISIONID,
      LA.ORDERMAINREVISIONID LABORDER_ID,
      LA.LABORDERDETAILREVISIONID LABORDER_DETAIL_ID,
      LA.TESTID TEST_ID,
      LA.TESTABBRE TEST_ABBREVIATION,
      LA.ACTIONNAME ACTION_NAME,
      LA.OLDVALUE OLD_VALUE,
      LA.NEWVALUE NEW_VALUE,
      CASE
         WHEN
            LA.ACTIONCREATEDBY = 'Vidaptor' 
         THEN
            0 
         WHEN
            LA.ACTIONCREATEDBY > 0 
         THEN
            TO_NUMBER(LA.ACTIONCREATEDBY) 
         ELSE
            LA.CREATEDBY 
      END
      AS ACTION_DONE_BY, 
      CASE
         WHEN
            TO_NUMBER(LA.ACTIONCREATEDBY) > 0 
         THEN
            LA.ACTIONCREATEDTIME 
         ELSE
            LA.CREATEDON 
      END
      AS ACTION_COMPLETED_ON, LA.REASON REASON_FOR_REJECTION_ACTION, LA.PATIENTID PATIENT_ID, LA.GROUPID GROUP_ID, LA.HOSPITALID HOSPITAL_ID 
   FROM
      LB_LABSERVICE.LBUTL_AUDITLOG LA 
   WHERE
      LA.ISACTIVE = 1 
)
, DISTINCT_USER_IDS AS 
(
   SELECT DISTINCT
      ACTION_DONE_BY 
   FROM
      AUDIT_LOG_DATA 
)
,
TENENT_USER_DATA AS 
(
   SELECT
      r.RMS_TENANT_ID,
      e.EMPLOYEE_CODE,
      u.USERNAME,
      u.FIRST_NAME || ' ' || u.LAST_NAME AS NAME 
   FROM
      SC_IAM.USER_ENTITY u 
      INNER JOIN
         SC_IAM.CSI_EMPLOYEEINFO e 
         ON e.USERID = u.ID 
      INNER JOIN
         SC_IAM.REALM r 
         ON r.ID = u.REALM_ID
)
,
AUDITLOG_WITH_USER_NAME AS 
(
   SELECT
      A.TRANSACTION_REVISIONID,
      A.LABORDER_ID,
      A.LABORDER_DETAIL_ID,
      A.TEST_ID,
      A.TEST_ABBREVIATION,
      A.ACTION_NAME,
      A.OLD_VALUE,
      A.NEW_VALUE,
      A.ACTION_DONE_BY,
      (
         SELECT
            NAME 
         FROM
            TENENT_USER_DATA 
         WHERE
            RMS_TENANT_ID = A.GROUP_ID 
            AND EMPLOYEE_CODE = A.ACTION_DONE_BY 
      )
      ACTION_DONE_BY_NAME,
      A.ACTION_COMPLETED_ON,
      A.REASON_FOR_REJECTION_ACTION,
      A.PATIENT_ID,
      A.GROUP_ID,
      A.HOSPITAL_ID 
   FROM
      AUDIT_LOG_DATA A 
)
SELECT
   * 
FROM
   AUDITLOG_WITH_USER_NAME;