--1 execute following script and check whethere there are records appering
SELECT p.MAPPEDHOSPITALID,p.GROUPID,p.TESTMAINID,ORDERTYPEID,p.TATTYPEID,p.TATUNITREVISIONID,count(p.TESTMAINID),max(p.TESTTATCONFIGURATIONREVISIONID) 
	FROM LB_LABSERVICE.LBTDR_HOSPITALTESTTATCONFIGURATION p
		WHERE p.ISACTIVE = 1 AND p.STATUSREVISIONID = 2
		GROUP BY p.MAPPEDHOSPITALID,p.GROUPID,p.TESTMAINID,ORDERTYPEID,TATTYPEID,TATUNITREVISIONID
		HAVING count(p.TESTMAINID) > 1 ;

--2 if there are records then run following set 
CREATE TABLE LBTDR_HOSPITALTESTTATCONFIGURATION_15JUNE2021 AS SELECT * FROM LB_LABSERVICE.LBTDR_HOSPITALTESTTATCONFIGURATION lh;

--3 delete duplicates

DELETE FROM LB_LABSERVICE.LBTDR_HOSPITALTESTTATCONFIGURATION WHERE TESTTATCONFIGURATIONREVISIONID IN (
WITH 
	duplicate_all_with_max_LBTDR_HOSPITALTESTTATCONFIGURATION AS 
	(		
		SELECT p.MAPPEDHOSPITALID,p.GROUPID,p.TESTMAINID,ORDERTYPEID,p.TATTYPEID,p.TATUNITREVISIONID,count(p.TESTMAINID),
		max(p.TESTTATCONFIGURATIONREVISIONID) AS max_TESTTATCONFIGURATIONREVISIONID
		FROM LB_LABSERVICE.LBTDR_HOSPITALTESTTATCONFIGURATION p
		WHERE p.ISACTIVE = 1 AND p.STATUSREVISIONID = 2
		GROUP BY p.MAPPEDHOSPITALID,p.GROUPID,p.TESTMAINID,p.ORDERTYPEID,p.TATTYPEID,p.TATUNITREVISIONID
		HAVING count(p.TESTMAINID) > 1
),
	all_duplicates as
	(SELECT p.MAPPEDHOSPITALID,p.GROUPID,p.TESTMAINID,p.ORDERTYPEID,p.TATTYPEID,p.TATUNITREVISIONID,t.TESTTATCONFIGURATIONREVISIONID FROM duplicate_all_with_max_LBTDR_HOSPITALTESTTATCONFIGURATION p
		INNER JOIN LB_LABSERVICE.LBTDR_HOSPITALTESTTATCONFIGURATION t ON p.GROUPID = t.GROUPID AND p.TESTMAINID = t.TESTMAINID AND p.ORDERTYPEID = t.ORDERTYPEID and p.MAPPEDHOSPITALID = t.MAPPEDHOSPITALID AND p.TATTYPEID = t.TATTYPEID 
		WHERE t.ISACTIVE = 1 AND t.STATUSREVISIONID = 2
		),
LesThanMaxRecordsof AS 
(
	SELECT a.TESTTATCONFIGURATIONREVISIONID,a.TESTMAINID,a.ORDERTYPEID,a.TATTYPEID,a.TATUNITREVISIONID,a.GROUPID FROM all_duplicates a
	WHERE a.TESTTATCONFIGURATIONREVISIONID NOT IN (SELECT max_TESTTATCONFIGURATIONREVISIONID FROM duplicate_all_with_max_LBTDR_HOSPITALTESTTATCONFIGURATION)
	ORDER BY a.TESTMAINID 
)
SELECT * FROM LesThanMaxRecordsof;
--SELECT * FROM duplicate_all_with_max_LBTDR_TESTTATCONFIGURATION;
--SELECT TESTTATCONFIGURATIONREVISIONID FROM LesThanMaxRecordsof;
);


		
		