DELETE FROM BKP_LBPAT_MRNMAPPING  WHERE MRNMAPPINGREVISIONID IN(
WITH
	DuplicateTENNATMRNListWithMRNMAPPINGREVISIONID AS 
	(
		SELECT lp.TENNATMRN, lp.LOCALMRN, count(lp.TENNATMRN), max(lp.MRNMAPPINGREVISIONID) maxMRNMAPPINGREVISIONID FROM BKP_LBPAT_MRNMAPPING lp 
		GROUP BY lp.GROUPID, lp.TENNATMRN, lp.LOCALMRN HAVING count(lp.TENNATMRN) > 1 ORDER BY lp.GROUPID,lp.TENNATMRN
	)
	,
	AllRowsForDuplicateTENNATMRNs AS 
	(
		SELECT lp.TENNATMRN,lp.LOCALMRN,lp.MRNMAPPINGREVISIONID FROM BKP_LBPAT_MRNMAPPING lp WHERE lp.TENNATMRN IN 
		( SELECT p.TENNATMRN FROM DuplicateTENNATMRNListWithMRNMAPPINGREVISIONID p) ORDER BY lp.TENNATMRN 
	)
	,
	LesThanMaxRecordsofTENNATMRN AS 
	(
		SELECT lp.MRNMAPPINGREVISIONID,lp.TENNATMRN,lp.LOCALMRN FROM AllRowsForDuplicateTENNATMRNs lp WHERE lp.MRNMAPPINGREVISIONID NOT IN 
		(SELECT maxMRNMAPPINGREVISIONID FROM DuplicateTENNATMRNListWithMRNMAPPINGREVISIONID) ORDER BY lp.TENNATMRN
	)
	
	--SELECT * FROM LesThanMaxRecordsofTENNATMRN
	SELECT MRNMAPPINGREVISIONID FROM LesThanMaxRecordsofTENNATMRN);


--CREATE UNIQUE INDEX Unique_BKP_LBPAT_MRNMAPPING ON BKP_LBPAT_MRNMAPPING (GROUPID,TENNATMRN,LOCALMRN);
	
