--1 execute following script and check whethere there are records appering
	SELECT p.GROUPID,p.MAPPEDHOSPITALID,p.TESTMAINID,p.TESTMAINSUBCODE,count(p.TESTMAINSUBCODE),max(p.TESTMAINPACKAGEREVISIONID) AS max_TESTMAINPACKAGEREVISIONID
		FROM LB_LABSERVICE.LBTDR_HOSPITALTESTMAINPACKAGE p 
		WHERE p.ISACTIVE = 1 AND p.STATUSREVISIONID = 2
		GROUP BY p.MAPPEDHOSPITALID,p.GROUPID,p.TESTMAINID,p.TESTMAINSUBCODE
		HAVING count(p.TESTMAINSUBCODE) > 1 
		
--2 if there are records then run following set 
CREATE TABLE JCBKP_LBTDR_HOSPITALTESTMAINPACKAGE AS SELECT * FROM LB_LABSERVICE.LBTDR_HOSPITALTESTMAINPACKAGE lh;

--3 delete duplicates

DELETE FROM LB_LABSERVICE.LBTDR_HOSPITALTESTMAINPACKAGE WHERE TESTMAINPACKAGEREVISIONID IN (
WITH 
	duplicate_all_with_max_TESTMAINPACKAGEREVISIONID AS 
	(
		SELECT p.GROUPID,p.MAPPEDHOSPITALID,p.TESTMAINID,p.TESTMAINSUBCODE,count(p.TESTMAINSUBCODE),max(p.TESTMAINPACKAGEREVISIONID) AS max_TESTMAINPACKAGEREVISIONID
		FROM LB_LABSERVICE.LBTDR_HOSPITALTESTMAINPACKAGE p 
		WHERE p.ISACTIVE = 1 AND p.STATUSREVISIONID = 2
		GROUP BY p.MAPPEDHOSPITALID,p.GROUPID,p.TESTMAINID,p.TESTMAINSUBCODE
		HAVING count(p.TESTMAINSUBCODE) > 1 
),
	all_duplicates as
	(SELECT p.GROUPID,p.MAPPEDHOSPITALID,p.TESTMAINID,p.TESTMAINSUBCODE,t.TESTMAINPACKAGEREVISIONID FROM duplicate_all_with_max_TESTMAINPACKAGEREVISIONID p
		INNER JOIN LB_LABSERVICE.LBTDR_HOSPITALTESTMAINPACKAGE t ON p.GROUPID = t.GROUPID AND p.MAPPEDHOSPITALID = t.MAPPEDHOSPITALID AND p.TESTMAINID = t.TESTMAINID 
		AND p.TESTMAINSUBCODE = t.TESTMAINSUBCODE
		),
LesThanMaxRecordsof AS 
(
	SELECT a.TESTMAINPACKAGEREVISIONID,a.TESTMAINID,a.TESTMAINSUBCODE,a.MAPPEDHOSPITALID,a.GROUPID FROM all_duplicates a
	WHERE a.TESTMAINPACKAGEREVISIONID NOT IN (SELECT max_TESTMAINPACKAGEREVISIONID FROM duplicate_all_with_max_TESTMAINPACKAGEREVISIONID)
	ORDER BY a.TESTMAINSUBCODE 
)
SELECT TESTMAINPACKAGEREVISIONID FROM LesThanMaxRecordsof
);

