INSERT INTO LBUTL_AUDITLOG_HISTORY_TEMP
WITH 
		MedicalVerified_Orderids AS 
		(
			SELECT * FROM 
			(
				SELECT DISTINCT lv.LABORDERID,lv.RESULTSTATUS,lv.MODIFIEDON FROM LBRST_VALUEBASEDRESULT lv 
				UNION
				SELECT DISTINCT lt.LABORDERID ,lt.RESULTSTATUS,lt.MODIFIEDON FROM LBRST_TEXTBASEDRESULT lt
				UNION
				SELECT DISTINCT lm.LABORDERID,lm.RESULTSTATUS,lm.MODIFIEDON FROM LBRST_MICROBIOLOGYRESULT lm
				UNION
				SELECT DISTINCT lh.LABORDERID,lh.RESULTSTATUS,lh.MODIFIEDON FROM LBRST_HISTOPATHALOGYRESULT lh
			)
			WHERE RESULTSTATUS = 4 AND MODIFIEDON <= '12-JUN-21'
		),
		Ordered_Orderids AS 
		(
			SELECT * FROM 
			(
				SELECT DISTINCT lv.LABORDERID,lv.RESULTSTATUS,lv.MODIFIEDON FROM LBRST_VALUEBASEDRESULT lv 
				UNION
				SELECT DISTINCT lt.LABORDERID ,lt.RESULTSTATUS,lt.MODIFIEDON FROM LBRST_TEXTBASEDRESULT lt
				UNION
				SELECT DISTINCT lm.LABORDERID,lm.RESULTSTATUS,lm.MODIFIEDON FROM LBRST_MICROBIOLOGYRESULT lm
				UNION
				SELECT DISTINCT lh.LABORDERID,lh.RESULTSTATUS,lh.MODIFIEDON FROM LBRST_HISTOPATHALOGYRESULT lh
			)
			WHERE RESULTSTATUS = 1 AND MODIFIEDON <= '12-JUN-21'
		),
		Resulted_Orderids AS 
		(
			SELECT * FROM 
			(
				SELECT DISTINCT lv.LABORDERID,lv.RESULTSTATUS,lv.MODIFIEDON FROM LBRST_VALUEBASEDRESULT lv 
				UNION
				SELECT DISTINCT lt.LABORDERID ,lt.RESULTSTATUS,lt.MODIFIEDON FROM LBRST_TEXTBASEDRESULT lt
				UNION
				SELECT DISTINCT lm.LABORDERID,lm.RESULTSTATUS,lm.MODIFIEDON FROM LBRST_MICROBIOLOGYRESULT lm
				UNION
				SELECT DISTINCT lh.LABORDERID,lh.RESULTSTATUS,lh.MODIFIEDON FROM LBRST_HISTOPATHALOGYRESULT lh
			)
			WHERE RESULTSTATUS = 1 AND MODIFIEDON <= '12-JUN-21'
		),
		VerifiedLevel1_Orderids AS 
		(
			SELECT * FROM 
			(
				SELECT DISTINCT lv.LABORDERID,lv.RESULTSTATUS,lv.MODIFIEDON FROM LBRST_VALUEBASEDRESULT lv 
				UNION
				SELECT DISTINCT lt.LABORDERID ,lt.RESULTSTATUS,lt.MODIFIEDON FROM LBRST_TEXTBASEDRESULT lt
				UNION
				SELECT DISTINCT lm.LABORDERID,lm.RESULTSTATUS,lm.MODIFIEDON FROM LBRST_MICROBIOLOGYRESULT lm
				UNION
				SELECT DISTINCT lh.LABORDERID,lh.RESULTSTATUS,lh.MODIFIEDON FROM LBRST_HISTOPATHALOGYRESULT lh
			)
			WHERE RESULTSTATUS = 1 AND MODIFIEDON <= '12-JUN-21'
		),
		Caccelled_Orderids AS 
		(
			SELECT * FROM 
			(
				SELECT DISTINCT lv.LABORDERID,lv.RESULTSTATUS,lv.MODIFIEDON FROM LBRST_VALUEBASEDRESULT lv 
				UNION
				SELECT DISTINCT lt.LABORDERID ,lt.RESULTSTATUS,lt.MODIFIEDON FROM LBRST_TEXTBASEDRESULT lt
				UNION
				SELECT DISTINCT lm.LABORDERID,lm.RESULTSTATUS,lm.MODIFIEDON FROM LBRST_MICROBIOLOGYRESULT lm
				UNION
				SELECT DISTINCT lh.LABORDERID,lh.RESULTSTATUS,lh.MODIFIEDON FROM LBRST_HISTOPATHALOGYRESULT lh
			)
			WHERE RESULTSTATUS = 1 AND MODIFIEDON <= '12-JUN-21'
		),
		Rerun_Orderids AS 
		(
			SELECT * FROM 
			(
				SELECT DISTINCT lv.LABORDERID,lv.RESULTSTATUS,lv.MODIFIEDON FROM LBRST_VALUEBASEDRESULT lv 
				UNION
				SELECT DISTINCT lt.LABORDERID ,lt.RESULTSTATUS,lt.MODIFIEDON FROM LBRST_TEXTBASEDRESULT lt
				UNION
				SELECT DISTINCT lm.LABORDERID,lm.RESULTSTATUS,lm.MODIFIEDON FROM LBRST_MICROBIOLOGYRESULT lm
				UNION
				SELECT DISTINCT lh.LABORDERID,lh.RESULTSTATUS,lh.MODIFIEDON FROM LBRST_HISTOPATHALOGYRESULT lh
			)
			WHERE RESULTSTATUS = 1 AND MODIFIEDON <= '12-JUN-21'
		),
		
		MedicallyVerifieNotIn_Ordered AS 
		(
			SELECT * FROM MedicalVerified_Orderids 
			WHERE LABORDERID NOT IN 
			(
				SELECT LABORDERID FROM Ordered_Orderids
			)
		),
		MedicallyVerifieNotIn_Ordered_Resulted AS 
		(
			SELECT * FROM MedicallyVerifieNotIn_Ordered 
			WHERE LABORDERID NOT IN 
			(
				SELECT LABORDERID FROM Resulted_Orderids
			)
		),
		MedicallyVerifieNotIn_Ordered_Resulted_VerifiedLevel1 AS 
		(
			SELECT * FROM MedicallyVerifieNotIn_Ordered_Resulted 
			WHERE LABORDERID NOT IN 
			(
				SELECT LABORDERID FROM VerifiedLevel1_Orderids
			)
		),
		MedicallyVerifieNotIn_Ordered_Resulted_VerifiedLevel1_Caccelled AS 
		(
			SELECT * FROM MedicallyVerifieNotIn_Ordered_Resulted_VerifiedLevel1 
			WHERE LABORDERID NOT IN 
			(
				SELECT LABORDERID FROM Caccelled_Orderids
			)
		),
		MedicallyVerifieNotIn_Ordered_Resulted_VerifiedLevel1_Caccelled_Rerun AS 
		(
			SELECT * FROM MedicallyVerifieNotIn_Ordered_Resulted_VerifiedLevel1_Caccelled 
			WHERE LABORDERID NOT IN 
			(
				SELECT LABORDERID FROM Rerun_Orderids
			)
		)
		
--		SELECT count(*) FROM LBUTL_AUDITLOG la WHERE la.ORDERMAINREVISIONID IN 
--	(SELECT ll.LABORDERID FROM MedicallyVerifieNotIn_Ordered_Resulted_VerifiedLevel1_Caccelled_Rerun ll);
	--	SELECT * FROM MedicallyVerifieNotIn_Ordered_Resulted_VerifiedLevel1_Caccelled_Rerun;
	
		SELECT * FROM LBUTL_AUDITLOG la WHERE la.ORDERMAINREVISIONID IN 
	(SELECT ll.LABORDERID FROM MedicallyVerifieNotIn_Ordered_Resulted_VerifiedLevel1_Caccelled_Rerun ll)
	

		