DELETE FROM LBUTL_AUDITLOG la WHERE la.ORDERMAINREVISIONID IN (SELECT ORDERMAINREVISIONID FROM LBUTL_AUDITLOG_HISTORY_TEMP); 

INSERT INTO LBUTL_AUDITLOG_HISTORY SELECT * FROM LBUTL_AUDITLOG_HISTORY_TEMP;

TRUNCATE TABLE LBUTL_AUDITLOG_HISTORY_TEMP; 

--DELETE FROM LBUTL_AUDITLOG la WHERE la.ORDERMAINREVISIONID IN (SELECT ORDERMAINREVISIONID FROM LBUTL_AUDITLOG_HISTORY); 