--First Create Sequence
CREATE SEQUENCE LBUTL_AUDITLOG_HISTORY_TEMP_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999999999
    CYCLE
    CACHE 2;
	
--Create AuditLog TABLE

CREATE TABLE "LB_LABSERVICE"."LBUTL_AUDITLOG_HISTORY_TEMP" 
   ("AUDITLOGID" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"ISACTIVE" NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATEDON" TIMESTAMP (7) NOT NULL ENABLE, 
	"MODIFIEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIEDON" TIMESTAMP (7) NOT NULL ENABLE, 
	"APPROVEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"APPROVEDON" TIMESTAMP (7) NOT NULL ENABLE, 
	"ROWVERSION" TIMESTAMP (7) NOT NULL ENABLE, 
	"HOSPITALID" NUMBER(10,0) DEFAULT 59 NOT NULL ENABLE, 
	"GROUPID" NUMBER(10,0) DEFAULT 58 NOT NULL ENABLE, 
	"LABID" NUMBER(*,0) DEFAULT 3 NOT NULL ENABLE, 
	"TRANSACTIONREVISIONID" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"LABORDERDETAILREVISIONID" NUMBER(10,0) DEFAULT 0, 
	"ACTIONNAME" VARCHAR2(4000 BYTE) DEFAULT ' ' NOT NULL ENABLE, 
	"ORDERMAINREVISIONID" NUMBER(10,0) DEFAULT 0, 
	"TESTID" NUMBER(10,0) DEFAULT 0, 
	"OLDVALUE" VARCHAR2(4000 BYTE), 
	"NEWVALUE" VARCHAR2(4000 BYTE), 
	"ACTIONCREATEDTIME" TIMESTAMP (6), 
	"AUDITID" NUMBER(10,0) DEFAULT "LB_LABSERVICE"."LBUTL_AUDITLOG_HISTORY_TEMP_SEQ"."NEXTVAL", 
	"REASON" NVARCHAR2(2000), 
	"ACTIONCREATEDBY" NVARCHAR2(2000), 
	"TESTABBRE" NVARCHAR2(50), 
	"PATIENTID" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "LBUTL_AUDITLOG_HISTORY_TEMP_PK" PRIMARY KEY ("AUDITLOGID"));
	 
--Now insert data using Second script "Moving status 4 auditlog records - script 2"

--Rollback Script
----------------------------
--DROP TABLE LBUTL_AUDITLOG_HISTORY_TEMP;
--DROP SEQUENCE LBUTL_AUDITLOG_HISTORY_TEMP_SEQ;